### ISSUE TITLE
Support for Smart Wi-Fi Garage Door Opener (MSG100)

### ISSUE THREAD

**Issue by tbones1** [homebridge-plugins/homebridge-meross#4]
I have a Meross Smart Wi-Fi Garage Door Opener. It would be tops if you were able to extend this plug-in to work with it :) I played around with various settings but haven't had much luck. I've dumped out the network traffic that is sent from the iOS app when you trigger an open and close. 

**Open Garage Door**
{
	"header": {
		"messageId": "xyz",
		"namespace": "Appliance.GarageDoor.State",
		"triggerSrc": "iOS",
		"method": "SETACK",
		"payloadVersion": 1,
		"from": "/appliance/xyz/publish",
		"timestamp": xyz,
		"timestampMs": xyz,
		"sign": "xyz"
	},
	"payload": {
		"state": {
			"channel": 0,
			"open": 0,
			"lmTime": xyz,
			"execute": 1
		}
	}
}

**Close Garage Door**
	"header": {
		"messageId": "xyz",
		"namespace": "Appliance.GarageDoor.State",
		"triggerSrc": "iOS",
		"method": "SETACK",
		"payloadVersion": 1,
		"from": "/appliance/xyz/publish",
		"timestamp": xyz,
		"timestampMs": xyz,
		"sign": "xyz"
	},
	"payload": {
		"state": {
			"channel": 0,
			"open": 1,
			"lmTime": xyz,
			"execute": 1
		}
	}
}

**Comment by donavanbecker** [comment]
You can submit a Pull Request for this and i can merge it.

**Comment by tbones1** [comment]
Awesome. Sorry I haven't used GitHub before, should I recreate above under the Pull section?

**Comment by donavanbecker** [comment]
No, If you are able code this to work with this plugin i can merge it with this plugin so you can use the garage door opener on this plugin. I can't add it myself.

**Comment by tbones1** [comment]
Okay cheers, I now understand a bit more about how GitHub works 👍

**Comment by donavanbecker** [comment]
It’s not that I don’t want to, I just don’t know how too. And don’t have the product to test it

**Comment by dylanfrankcom** [comment]
Hey @tbones1! Thanks for including the payload of the device. The sent request looks pretty similar to other devices so I think it can be implemented. I will look into this over the coming days. As @donavanbecker mentioned, neither of us have the product but we can try our best and see what we can do.

**Comment by tbones1** [comment]
Hi @dylanfrankcom, that would be amazing. I'm happy to do some testing and help with any troubleshooting.

**Comment by dylanfrankcom** [comment]
@tbones1 Could you join the [Homebridge Discord Server](https://discord.gg/kqNCe2D) server and shoot me a message on there? Looking to add support and just require some additional information.

**Comment by donavanbecker** [comment]
Just released [Version 1.1.0](https://github.com/donavanbecker/homebridge-meross/releases/tag/v1.1.0), if you want to give it a try. This does not include support for the garage door, we need you to reach out on discord so that we can get more info from you.

**Comment by lami974** [comment]
Hello, I'm not a developer, but I have two MSG100s. As far as I can, I can help you with the tests. What do you need for the next. I also dumped the network and I have the same thing as @tbones1

**Comment by donavanbecker** [comment]
@lami974 can you reach out to us on the homebridge discord server?

**Comment by lami974** [comment]
« Oznu/homebridge:no-avahi » on NAS Synology server, in docker. « Alpine Linux (3.11.6) »

**Comment by donavanbecker** [comment]
[Homebridge Discord Server](https://discord.gg/Z8jmyvb)

**Comment by HarrySteff** [comment]
It would be very great if this plugin would support the msg100. I also own such a device. If I can do anything except coding, please give me info. Thank you!

**Comment by donavanbecker** [comment]
@HarrySteff Are you on the discord server?

**Comment by HarrySteff** [comment]
No, at the moment i am not... i will try it later...

**Comment by Vati80** [comment]
Hi donavanbecker,

Thank you very much for your efforts!
I would also like to offer my support, for testing. I have a Meross MSG100 Garage Door Opener. HomeBridge runs on a Raspberry Pi. I have a Discord Account too.

Cheers Vati

**Comment by tbones1** [comment]
> @tbones1 Could you post the information from the `GET` / `GETACK` request too? Also, is the `lmTime` value in each payload different?

Posted in Discord
ImTime is different and appears to be UNIX time

**Comment by CocoaBob** [comment]
I got one, since I thought it was already supported by this plugin  😂

After collecting several HTTP requests, I noticed that the `messageId` and `sign` are always changing, and they are all 32 characters. I guess they were AES 128 hash codes calculated from a key + current timestamp + some other factor.

Let me try to use a Jailbroken iPhone to analyze their iOS app.

**Comment by CocoaBob** [comment]
OK, forget about what I said just now, I noticed that there was a firmware update, which said it would improve the security of open/close... But after updating the firmware, now I can control the door with Postman 😂

Let me check it further.

**Comment by CocoaBob** [comment]
The garage door support is so complicated, I underestimated it and just spent one day to debug the logic. My neighbours may notice my garage door kept closing/opening during the night 😂

Here's my pull request https://github.com/homebridge-plugins/homebridge-meross/pull/29

Problems left:
1. How can we get open/close notifications from Meross?
I've observed the traffic, the iOS app is relying on Apple's Push Notification Service to receive the state updates.
2. Meross can't stop closing a door (And my implementation will be messed up if we try to stop closing/opening)
3. Meross doesn't support stopped state
4. Meross doesn't support obstruction state

**Comment by donavanbecker** [comment]
> The garage door support is so complicated, I underestimated it and just spent one day to debug the logic. My neighbours may notice my garage door kept closing/opening during the night 😂
> 
> 
> 
> Here's my pull request https://github.com/homebridge-plugins/homebridge-meross/pull/29
> 
> 
> 
> Problems left:
> 
> 1. How can we get open/close notifications from Meross?
> 
> I've observed the traffic, the iOS app is relying on Apple's Push Notification Service to receive the state updates.
> 
> 2. Meross can't stop closing a door (And my implementation will be messed up if we try to stop closing/opening)
> 
> 3. Meross doesn't support stopped state
> 
> 4. Meross doesn't support obstruction state

I have merged this in the latest beta, if you would like to try, follow these [instructions](https://github.com/homebridge-plugins/homebridge-meross/wiki/Beta).

**Comment by Vati80** [comment]
Hello, thank you for the great work. I installed the beta today. What content do I have to enter in the fields: "messageId", "timestamp" and "sign"?
Cheers Vati

**Comment by CocoaBob** [comment]
@Vati80 Yes, you still need to sniffer the traffic and get the `messageId`, `timestamp` and `sign` from the app's request. Here's a screenshot of the settings in **Homebridge Config UI X**.

![image](https://user-images.githubusercontent.com/489666/82733256-a26ed000-9ce0-11ea-8ac1-fc00de084752.png)

And here's another screenshot of my Homebridge `config.json` file.
![image](https://user-images.githubusercontent.com/489666/82733314-098c8480-9ce1-11ea-9790-13e70c7741f6.png)

**Comment by CocoaBob** [comment]
Sorry, I made a mistake in the last commit, just fixed it this morning, please try again after merging PR https://github.com/homebridge-plugins/homebridge-meross/pull/30 .

**Comment by donavanbecker** [comment]
> Sorry, I made a mistake in the last commit, just fixed it this morning, please try again after merging PR https://github.com/homebridge-plugins/homebridge-meross/pull/30 .

#30 has been merged into latest beta.

**Comment by Vati80** [comment]
@CocoaBob  i sniff my traffic with the Wireshark app (OS X). I try it for hours... sorry but I can't find the entries for "messageId", "timestamp" and "sign". I found the IP, respectively the "Meross-Smart-Garage.fritz.box" entries. When i open the line i don't see the searched entries. What else can I do

> Frame 792: 98 bytes on wire (784 bits), 98 bytes captured (784 bits) on interface en1, id 0
    Interface id: 0 (en1)
        Interface name: en1
        Interface description: Ethernet 2
    Encapsulation type: Ethernet (1)
    Arrival Time: May 23, 2020 20:13:31.057012000 CEST
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1590257611.057012000 seconds
    [Time delta from previous captured frame: 0.024757000 seconds]
    [Time delta from previous displayed frame: 0.025423000 seconds]
    [Time since reference or first frame: 1.815874000 seconds]
    Frame Number: 792
    Frame Length: 98 bytes (784 bits)
    Capture Length: 98 bytes (784 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:icmp:data]
    [Coloring Rule Name: ICMP]
    [Coloring Rule String: icmp || icmpv6]
Ethernet II, Src: ChengduM_xx:xx:xx (xx:xx:xx:xx:xx:xx), Dst: XXXXX-Mac-Pro.fritz.box (xx:xx:xx:xx:xx:xx)
    Destination: XXXXX-Mac-Pro.fritz.box (xx:xx:xx:xx:xx:xx)
        Address: XXXXX-Mac-Pro.fritz.box (xx:xx:xx:xx:xx:xx)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: ChengduM_xx:xx:xx (xx:xx:xx:xx:xx:xx)
        Address: ChengduM_xx:xx:xx (xx:xx:xx:xx:xx:xx)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: Meross-Smart-Garage.fritz.box (192.xxx.xxx.xxx), Dst: XXXXX-Mac-Pro.fritz.box (192.xxx.xxx.xxx)
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 84
    Identification: 0xf37d (62333)
    Flags: 0x0000
        0... .... .... .... = Reserved bit: Not set
        .0.. .... .... .... = Don't fragment: Not set
        ..0. .... .... .... = More fragments: Not set
    Fragment offset: 0
    Time to live: 255
    Protocol: ICMP (1)
    Header checksum: 0xe1cb [validation disabled]
    [Header checksum status: Unverified]
    Source: Meross-Smart-Garage.fritz.box (192.xxx.xxx.xxx)
    Destination: XXXXX-Mac-Pro.fritz.box (192.xxx.xxx.xxx)
Internet Control Message Protocol
    Type: 0 (Echo (ping) reply)
    Code: 0
    Checksum: 0xe5fa [correct]
    [Checksum Status: Good]
    Identifier (BE): 18243 (0x4743)
    Identifier (LE): 17223 (0x4347)
    Sequence number (BE): 3581 (0x0dfd)
    Sequence number (LE): 64781 (0xfd0d)
    [Request frame: 786]
    [Response time: 25.423 ms]
    Data (56 bytes)
        Data: 070707070707070707070707070707070707070707070707…
        Text: \a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a\a
        [Length: 56]
>

**Comment by donavanbecker** [comment]
@Vati80 try using the [Getting Credentials](https://github.com/homebridge-plugins/homebridge-meross/wiki/Getting-Credentials) wiki.

**Comment by Vati80** [comment]
@donavanbecker oh man... Thank you so much! It was done in 2 minutes. Before, I tried for hours...

cheers Vati

**Comment by hardstylle** [comment]
Hey,
I hacked together garage door support by calling a python script using this library: https://github.com/albertogeniola/MerossIot
I was going to try and do it purely in js but it seems like you’re already close to having it working.

**Comment by donavanbecker** [comment]
@CocoaBob @Vati80 @tbones1 @HarrySteff, with the latest beta. how is everything working? Any issues?
If there are no issues, do you think this is ready for release?
Since @dylanfrankcom and myself don't have the MSG-100, we can't really test this so need your results to know when to release.

**Comment by CocoaBob** [comment]
Currently I'm using a fixed duration (20 sec) to tell if the door is OPEN, but I see there's an option in the app to let users choose how long their opener will take to complete the opening (my screenshot shows `15s`).

I'm wondering if I should add that setting too, and remove the serial number setting (since it still works without serial number). But currently I'm too busy to WFH 😂, probably will have some time during the weekends. Let me see if I can add this option tonight.

And yes, @Vati80 @tbones1 @HarrySteff, please send me some feedbacks if you have any time to test it, thanks!

![IMG_B39265903039-1](https://user-images.githubusercontent.com/489666/82931592-25985c00-9f55-11ea-8087-cf57dfb02bbe.jpeg)

**Comment by Vati80** [comment]
Hi @donavanbecker and @CocoaBob ,

I have extensively tested the meross plugin for the Last 2-3 days. In my opinion, it works great. I also tested different WLAN with the same settings in Config.json. So far... I have not found any errors and I am really very happy with them. A big compliment to you for this Great work! I love it.

Cheers Vati

**Comment by HarrySteff** [comment]
Thank you for all your work, until now I unfortunately could not test it... but I will definitely do so in the next couple of days. Thank you so much...

**Comment by lami974** [comment]
Hi @donavanbecker @CocoaBob 

It works great for me on my two MSG 100. Thank you so much…

**Comment by donavanbecker** [comment]
I have release Version 2.0.0:

#### Changes
- added Support for MSG-100 (Garage Door Opener).

## IMPORTANT
#### Homebridge v1.0.0
- Changed homebridge requirement to be v1.0.0 or higher.

**Comment by Kokorone** [comment]
I have this same garage opener the MSG-100, but there is a parameter for the "duration of press" that needs to be added to the homebridge plugin. Its already being passed through as timestampMs right after the timestamp value. My garage opener requires a 2 second press (244ms in the request) for it to actually begin opening or closing so despite it being added to homebridge just fine, its not triggering when requested.

**Comment by CocoaBob** [comment]
@Kokorone I just tried the official Meross app, the `signal duration` can be set in the app, and will be saved to MSG-100 directly. (I captured the request) So I guess after setting the value, our Homebridge plugin should be able to Open/Close the opener correctly?

Based on what I captured, the `signal duration` setting is another HTTP request, the parameter isn't included in my Open/Close requests. If you could send me an example of the request, to see how `duration of press` parameter is included in Open/Close requests, that would be perfect.

Here's the `open the door` request captured on my side, I don't see the duration setting
```
{
    "payload": {
        "state": {
            "channel": 0,
            "uuid": "__UUID__",
            "open": 1
        }
    },
    "header": {
        "messageId": "__MESSAGE_ID__",
        "method": "SET",
        "from": "http:\/\/192.168.0.124\/config",
        "sign": "__SIGN__",
        "namespace": "Appliance.GarageDoor.State",
        "triggerSrc": "iOS",
        "timestamp": 1595540879,
        "payloadVersion": 1
    }
}
```

Here's the `set signal duration` request captured on my side
```
{
    "payload": {
        "config": {
            "signalDuration": 500
        }
    },
    "header": {
        "messageId": "__MESSAGE_ID__",
        "method": "SET",
        "from": "http:\/\/192.168.0.128\/config",
        "sign": "__SIGN__",
        "namespace": "Appliance.GarageDoor.Config",
        "triggerSrc": "iOS",
        "timestamp": 1595542266,
        "payloadVersion": 1
    }
}
```

**Comment by Kokorone** [comment]
> @Kokorone I just tried the official Meross app, the `signal duration` can be set in the app, and will be saved to MSG-100 directly. (I captured the request) So I guess after setting the value, our Homebridge plugin should be able to Open/Close the opener correctly?
> 
> Based on what I captured, the `signal duration` setting is another HTTP request, the parameter isn't included in my Open/Close requests. If you could send me an example of the request, to see how `duration of press` parameter is included in Open/Close requests, that would be perfect.
> 
> Here's the `open the door` request captured on my side, I don't see the duration setting
> 
> ```
> {
>     "payload": {
>         "state": {
>             "channel": 0,
>             "uuid": "__UUID__",
>             "open": 1
>         }
>     },
>     "header": {
>         "messageId": "__MESSAGE_ID__",
>         "method": "SET",
>         "from": "http:\/\/192.168.0.124\/config",
>         "sign": "__SIGN__",
>         "namespace": "Appliance.GarageDoor.State",
>         "triggerSrc": "iOS",
>         "timestamp": 1595540879,
>         "payloadVersion": 1
>     }
> }
> ```
> 
> Here's the `set signal duration` request captured on my side
> 
> ```
> {
>     "payload": {
>         "config": {
>             "signalDuration": 500
>         }
>     },
>     "header": {
>         "messageId": "__MESSAGE_ID__",
>         "method": "SET",
>         "from": "http:\/\/192.168.0.128\/config",
>         "sign": "__SIGN__",
>         "namespace": "Appliance.GarageDoor.Config",
>         "triggerSrc": "iOS",
>         "timestamp": 1595542266,
>         "payloadVersion": 1
>     }
> }
> ```

Interesting. Here is what I’m getting from the http capture app. 

{
  "header": {
    "messageId": "cb8d04916156ac32995b3990331d7659",
    "namespace": "Appliance.System.Online",
    "triggerSrc": "iOS",
    "method": "GETACK",
    "payloadVersion": 1,
    "from": "/appliance/1911080065387090804648e1e9111579/publish",
    "timestamp": 1595538826,
    "timestampMs": 244,
    "sign": "7b719b6dcb58e59757f28459386f59ca"
  },
  "payload": {
    "online": {
      "status": 1
    }
  }
}

I have 2 seconds configured in my Meross app for the MSG-100 but all toggling the switch in homebridge does is toggle it “off” then after a few seconds it turns back on and the garage does nothing.

**Comment by CocoaBob** [comment]
@Kokorone But it works in the official app? Strange, let me test more. And please let me know the hardware/firmware versions, maybe something is different.

**Comment by Kokorone** [comment]
@CocoaBob yup no issues at all with the app or the widget for the app. Here is a screenshot of the firmwares 
![E602E7EB-53EF-4C63-B17A-928FDB04DC35](https://user-images.githubusercontent.com/32761171/88344215-f2c1d880-ccf7-11ea-8c4c-e0429f83a2c8.png)

**Comment by CocoaBob** [comment]
@Kokorone 
This is the request you posted yesterday
```
{
  "header": {
    "messageId": "cb8d04916156ac32995b3990331d7659",
    "namespace": "Appliance.System.Online",
    "triggerSrc": "iOS",
    "method": "GETACK",
    "payloadVersion": 1,
    "from": "/appliance/1911080065387090804648e1e9111579/publish",
    "timestamp": 1595538826,
    "timestampMs": 244,
    "sign": "7b719b6dcb58e59757f28459386f59ca"
  },
  "payload": {
    "online": {
      "status": 1
    }
  }
}
```
Do you know where it was sent to? My captured request was sent to `http://192.168.0.128/config`

And do you have other Meross devices at home? For example, another smart switch?

**Comment by Kokorone** [comment]
@CocoaBob I only have the one meross device, with a static ip of 192.168.1.161. I grabbed the values from http catcher from http://192.168.1.161/config

**Comment by Kokorone** [comment]
@CocoaBob I may have found the problem, After opening and closing the garage 4 times, I see no network traffic other than the initial 2 requests to 192.168.1.161 with the /config. Closing and reopening the app is enough to make these two requests happen. I'm not sure how its possible for the opener to not send any traffic for the open and close commands though? 

![IMG_3412](https://user-images.githubusercontent.com/32761171/88443989-b9f53280-cdcf-11ea-924f-d504dd4d98b8.jpeg)

**Comment by Kokorone** [comment]
@CocoaBob unfortunately I can only chalk it up to meross having some firmware update that blocked the functionality between firmware 3.1.13 and 3.1.15. I've tried setting the unit back up with httpcatcher running and trying every possible parameter configuration, even going so far as to buy a new unit.
