### ISSUE TITLE
Support on/off for each sockets

### ISSUE THREAD

**Issue by TimLi20** [homebridge-plugins/homebridge-meross#40]
My Meross have 4 sockets, the meross can support turn each one on or off, can homebridge can do it? This is very useful to control every device in homekit.

**Comment by donavanbecker** [comment]
Please use issue template.

**Comment by donavanbecker** [comment]
@TimLi20 what model?

**Comment by TimLi20** [comment]
The model is mss426f

**Comment by donavanbecker** [comment]
Did you check out the [power strips](https://github.com/homebridge-plugins/homebridge-meross/wiki/Specific-Model-Configurations#mss420mss425—power-strips) wiki?
