### ISSUE TITLE
Meross Power Strip (MSS420F) Not Working

### ISSUE THREAD

**Issue by Lukabratzee** [homebridge-plugins/homebridge-meross#44]
This is the output I get from the Homebridge console logs

```json
(node:838) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'digest' of undefined
    at Meross.getOnCharacteristicHandler (/usr/lib/node_modules/homebridge-meross/index.js:327:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

My config is:

```json
        {
            "model": "MSS420F",
            "name": "Meross Strip",
            "deviceUrl": "192.168.1.199",
            "channel": 0,
            "messageId": "69f51bd4a3cee4bb3a0c9df9b5",
            "timestamp": 1592957079,
            "sign": "ef7dbc1e630b7242376bbacea5e3c89",
            "accessory": "Meross"
        }
```

I'm using HTTP Catcher, it returns a valid 200 response.

I originally posted on Reddit regarding the power strip, sorry it took so long!

**Comment by donavanbecker** [comment]
@Lukabratzee can you change your channel to 1 and let me know what you see?

**Comment by Lukabratzee** [comment]
I've made the change, no joy unfortunatly. 

I get a similar error on the console log:

```json
(node:10413) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'digest' of undefined
    at Meross.getOnCharacteristicHandler (/usr/lib/node_modules/homebridge-meross/index.js:327:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:10413) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by donavanbecker** [comment]
I need more info on your setup.

**Comment by Lukabratzee** [comment]
Sure, what do you need?

I'm running Homebridge, all over devices like Tuya, LifX run fine. 
Not sure what else I can mention, you put me on the spot haha.

**Comment by donavanbecker** [comment]
issue template has all questions in it.

**Comment by donavanbecker** [comment]
> I've made the change, no joy unfortunatly.
> 
> I get a similar error on the console log:
> 
> ```json
> (node:10413) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'digest' of undefined
>     at Meross.getOnCharacteristicHandler (/usr/lib/node_modules/homebridge-meross/index.js:327:34)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
> (node:10413) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> ```

also please provide updated config

**Comment by Lukabratzee** [comment]
Node.js Version: 12.8.0
NPM Version: 6.14.4
Homebridge Version: 1.1.1(latest)
Homebridge Meross Plugin Version: 2.3.0
Homebridge Config UI X Plugin Version: 4.23.0
Operating System: Ubuntu 18.04.4 LTS (GNU/Linux 5.3.0-59-generic x86_64)

### Config:

```json
        {
            "model": "MSS420F",
            "name": "Meross Strip",
            "deviceUrl": "192.168.1.199",
            "channel": 1,
            "messageId": "69f51bd4a3cee4bb3a0c9df9b5",
            "timestamp": 1592957079,
            "sign": "ef7dbc1e630b7242376bbacea5e3c89",
            "accessory": "Meross"
        }
```

**Comment by donavanbecker** [comment]
can you post everything you get from using one these [methods](https://github.com/homebridge-plugins/homebridge-meross/wiki/Getting-Credentials)? make sure you go into the merls app and turn each plug on and off for the power strip. Then send the requests for each plug. Thanks!

**Comment by Lukabratzee** [comment]
Sure thing, I toggled all 5 switches from OFF to ON (ALL, SW1/2/3/4)  and ON to OFF (SW1/2/3/4) and found their responses in HTTP Catcher.
Screenshotted them from iOS and uploaded here.

First batch are OFF to ON

![IMG_5316](https://user-images.githubusercontent.com/8959269/85926444-70c8c600-b897-11ea-9f29-514db5431e08.PNG)
![IMG_5317](https://user-images.githubusercontent.com/8959269/85926445-72928980-b897-11ea-9a9e-c84072887382.PNG)
![IMG_5318](https://user-images.githubusercontent.com/8959269/85926446-72928980-b897-11ea-9a56-65e6ee9d0d37.PNG)
![IMG_5319](https://user-images.githubusercontent.com/8959269/85926448-732b2000-b897-11ea-8509-28a83794c1f2.PNG)
![IMG_5320](https://user-images.githubusercontent.com/8959269/85926449-73c3b680-b897-11ea-9fa4-097404283137.PNG)

Second batch are ON to OFF

![IMG_5321](https://user-images.githubusercontent.com/8959269/85926513-ec2a7780-b897-11ea-9451-0ba6735d0da7.PNG)
![IMG_5322](https://user-images.githubusercontent.com/8959269/85926515-edf43b00-b897-11ea-80a3-d7e8df50803e.PNG)
![IMG_5323](https://user-images.githubusercontent.com/8959269/85926516-edf43b00-b897-11ea-8ee7-5acc7225f590.PNG)
![IMG_5324](https://user-images.githubusercontent.com/8959269/85926517-ee8cd180-b897-11ea-8fe4-cddc5ebfc207.PNG)

**Comment by donavanbecker** [comment]
@Lukabratzee Can you try changing the model to MS110, and see if it works? If it does we can try changing this for your model. ![image](https://user-images.githubusercontent.com/9875439/85931251-98646200-b888-11ea-99c1-8702f08f732d.jpeg)

**Comment by mrdanielm** [comment]
@donavanbecker FWIW... I've managed to successfully setup this exact power strip today using the guide on the WiKi and the correct model number in the config.

I used channel 1-4 and grabbed the credentials from the /config url using the Charles app

**Comment by Lukabratzee** [comment]
Apologies for taking so long to reply.
I changed my channel to 1-4, and I’ve made sure it’s MSS-110 1.0
There hasn’t been a change. I think the best thing for me to do is scrub the config part and set it up fresh from scratch, to see if I’m missing anything.

I’ve followed the wiki with HTTP Catcher but for a sanity check, I’ll use Charles.
I’ll do that tonight after work and update with my progress.

**Comment by Lukabratzee** [comment]
I wanted to post an update, I got it working!
Following the 4 channel guide, I altered the config and switched the model back to 420F.

Thank you for all your help.

```
        {
            "model": "MSS420F",
            "name": "Outlet 1",
            "deviceUrl": "192.168.1.199",
            "channel": 1,
            "messageId": "xxx",
            "timestamp": xxx,
            "sign": "xxx",
            "accessory": "Meross"
        },
        {
            "model": "MSS420F",
            "name": "Outlet 2",
            "deviceUrl": "192.168.1.199",
            "channel": 2,
            "messageId": "xxx",
            "timestamp": xxx,
            "sign": "xxx",
            "accessory": "Meross"
        },
        {
            "model": "MSS420F",
            "name": "Outlet 3",
            "deviceUrl": "192.168.1.199",
            "channel": 3,
            "messageId": "xxx",
            "timestamp": xxx,
            "sign": "xxx",
            "accessory": "Meross"
        },
        {
            "model": "MSS420F",
            "name": "Outlet 4",
            "deviceUrl": "192.168.1.199",
            "channel": 4,
            "messageId": "xxx",
            "timestamp": xxx,
            "sign": "xxx",
            "accessory": "Meross"
        }
```

**Comment by donavanbecker** [comment]
> I wanted to post an update, I got it working!
> 
> Following the 4 channel guide, I altered the config and switched the model back to 420F.
> 
> 
> 
> Thank you for all your help.

Good to hear! Glad you got it!

**Comment by vasilinho23** [comment]
Hi guys,
I have the same error for Meross Power Strip, but for MSS425F:
`(node:2085) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'digest' of undefined
    at Meross.getOnCharacteristicHandler (/homebridge/node_modules/homebridge-meross/src/index.ts:352:34)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`
My Config is:
`"accessories": [
        {
            "model": "MSS425F",
            "name": "Living Room Outlet 1",
            "deviceUrl": "192.168.1.95",
            "channel": 1,
            "messageId": "xxxx",
            "timestamp": xxx,
            "sign": "xxx",
            "accessory": "Meross"
        },
        {
            "model": "MSS425F",
            "name": "Living Room Outlet 2",
            "deviceUrl": "192.168.1.95",
            "channel": 2,
            "messageId": "xxx",
            "timestamp": xxx,
            "sign": "xxx",
            "accessory": "Meross"
        },
        {
            "model": "MSS425F",
            "name": "Living Room Outlet 3",
            "deviceUrl": "192.168.1.95",
            "channel": 3,
            "messageId": "xxx",
            "timestamp": xxx,
            "sign": "xxx",
            "accessory": "Meross"
        },
        {
            "model": "MSS425F",
            "name": "Living Room Outlet 4",
            "deviceUrl": "192.168.1.95",
            "channel": 4,
            "messageId": "xxx",
            "timestamp": xxx,
            "sign": "xxx",
            "accessory": "Meross"
        },
        {
            "model": "MSS425F",
            "name": "Living Room Outlet 5",
            "deviceUrl": "192.168.1.95",
            "channel": 5,
            "messageId": "xxx",
            "timestamp": xxx,
            "sign": "xxx",
            "accessory": "Meross"
        }
    ],`

My Versions:
Node.js Version: v12.19.0
NPM Version: 6.14.8
Homebridge Version: v1.2.3
Homebridge Meross Plugin Version: v3.2.0
Homebridge Config UI X Plugin Version: 4.29.0
Operating System: Alpine Linux v3.12

Could someone help me please?
I've read all comments, but didn't find out how did you resolve it.

Thanks,
Vasili
