### ISSUE TITLE
Can't configure my 2 Meross MSS310

### ISSUE THREAD

**Issue by overflywingo** [homebridge-plugins/homebridge-meross#50]
Hi
I recently installed Homebridge-Meros (v2.3.0) and I'm trying to do the setup for my 2 plugs. 
The Wiki is a bit unclear to me.  

- Because it's not clear to me if I have to use **both** HTTP Catcher AND Charles to collect the  data or if using just one of the two if enough ? 

- First I used HTTP catcher to gather those 3 fields, messageId, timestamp &  sign ....  but here already a problem because for a single power on on a plug  (in the MEROSS app) .. HTTP catcher is grabbing several posts, having all "/config 200 application/json" but when opening them they have all different informations for "messageId, timestamp &  sign" so I don't understand why those differences in data and also which is the good one to select ?  So I just randomly pick up data out of one of the post and used them in the Hombrige-Meross config.  On top,  I added 2 additional parameter "version" and "innerIp" ... but not OK and erros in the log (see below)

-Second, I used Charlie (on MAC) to grab the required information  .. (got again different values for messageId, timestamp &  sign)  to  but same result  at the end , errors

**My config :** 

{
            "model": "MSS310",
            "name": "MEROSS 1",
            "deviceUrl": "192.168.1.161",
            "channel": 0,
            "messageId": "f67b3fb76156........d08239bc027dee",
            "timestamp": 1594374788,
            "sign": "a92dcc56b1eb14........f03790b74384",
            "accessory": "Meross",
            "version": "1.0.0",
            "innerIp": "192.168.1.161"
        },
        {
            "model": "MSS310",
            "name": "MEROSS 2",
            "deviceUrl": "192.168.1.162",
            "channel": 0,
            "messageId": "04da0d2e4070......f1f81ca5cd729",
            "timestamp": 1594374790,
            "sign": "d287ad92d09e......a253cf8f6f2b",
            "accessory": "Meross",
            "version": "1.0.0",
            "innerIp": "192.168.1.162"
        }

**Errors**

(node:1155) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'togglex' of undefined
    at Meross.getOnCharacteristicHandler (/usr/local/lib/node_modules/homebridge-meross/index.js:327:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1155) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:1155) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'togglex' of undefined
    at Meross.getOnCharacteristicHandler (/usr/local/lib/node_modules/homebridge-meross/index.js:327:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1155) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
[7/10/2020, 12:14:35 PM] [MEROSS 1] Set failed: false
[7/10/2020, 12:14:38 PM] [MEROSS 2] Set failed: false

Thanks for your help 

Eugène

**Comment by dylanfrankcom** [comment]
Hey @overflywingo, looks like the request is the same as the MSS110 V1.0. Try changing the device model to that in your config (`"model": "MSS110-1"`) or homebridgeUI settings, whichever you prefer. I can get this changed for an upcoming release in which case your config will break again when you update. Just a heads up.

**Comment by overflywingo** [comment]
Hi Dylan,  indeed is the same as MSS110.   I changed the model in the config and everything is now working perfectly. Great ! 
Also your explanations about HTTPCatcher and Charles are very clear .. as well as your explanations/clarifications about messageId, timestamp & sign changing all the times ... but not being an issue because of a valid combination. 
I think  all those explanations should be added to the Wiki to help novices ... like me.

**Comment by donavanbecker** [comment]
@overflywingo You should be able to update the wiki?

**Comment by ThomasTom86** [comment]
Hello! I'm new here and have a problem. Since yesterday I have been trying to connect my meross sockets to homebridge. I have an MSS310 (firmware 1.1.18 / hardware 1.0.0) and an MSS210 ( firmware 1.1.12 / hardware 1.0.0). I added both to homebridge as described in the description, unfortunately they cannot be switched via homebridge / home app. 
Thank's Tom

[06/12/2020, 13:43:20] [Aquarium Licht] Set failed: false
[06/12/2020, 13:43:24] [Aquarium Technik] Set failed: false


{
            "model": "MSS210",
            "name": "Aquarium Technik",
            "deviceUrl": "192.168.1.17",
            "channel": 0,
            "messageId": "ea92923a70b7f4fee68c941adc27a36c",
            "timestamp": 1607256877,
            "sign": "d1b5644f42f1a7e92d55c154c638624c",
            "accessory": "Meross"
        },
        {
            "model": "MSS310",
            "name": "Aquarium Licht",
            "deviceUrl": "192.168.1.18",
            "channel": 0,
            "messageId": "b65e9d1236e762140c6c0edc5279ea1d",
            "timestamp": 1607257040,
            "sign": "e9c53eeacf6378faf9450984f547f4ed",
            "accessory": "Meross"
        }
