### ISSUE TITLE
Unable to find 'MessageID' anywhere in the HTTP Catcher logs

### ISSUE THREAD

**Issue by chowdarygm** [homebridge-plugins/homebridge-meross#51]
**Describe Your Problem:**
Unable to find 'MessageID' anywhere in the HTTP Catcher logs, not sure what has changed recently. I ran the logs 5-6 times (My neighbors will curse me if I open and close garage door any more than this :P )

**Logs:**
Attached below are the screenshots of the HTTP catcher app logs

[https://imgur.com/a/GOXGnub](url)

**Comment by dylanfrankcom** [comment]
Hello, @chowdarygm. I think you have to click into those logs to see the request headers. Haven't used HTTPCatcher in a while so I might be wrong.

**Comment by TautFlorian** [comment]
@chowdarygm Works fine for me. Could you try this:
1. Open up the meross app (and already click on the outlet if you have surge protector)
2. After that go back to HTTP Catcher and then start the VPN connection.
3. Go back an turn on the outlet.
4. In HTTP Catcher search for a POST to a local ip-address with "/config"

I had those results too some times when meross app crashes.
These seem to be the default checks to meross servers f.e. to collect update data.

**Comment by chowdarygm** [comment]
Got it solved. All my IoT devices are connected to a guest network. As my iPhone was connected to the main network, it was not able to get the logs with IP address. Once I connected my device to the guest network, it was able to see the required information.
